image: python:3.6

pipelines:
  branches:
    master:
      - step:
        caches:
          - pip
        script:
          - pip install requests pysocks idna cryptography requests[security] cx_Freeze
          - git clone https://bitbucket.org/anon_a/dbooru.git
          - cd dbooru
          - git fetch
          - git checkout master
          - git pull
          - mv settings_file.py settings_file.py.1
          - python setup.py build
          - cp settings_file.py.1 build/*/settings_file.py
          - cd build/*
          - tar -cvf DBooru.tar *
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"DBooru.tar"