image: python:3.6

pipelines:
  default:
    - step:
        caches:
          - pip
          - pip install requests pysocks idna cryptography requests[security] cx_Freeze
          - git clone https://bitbucket.org/anon_a/dbooru.git
          - cd dbooru
          - git fetch
          - git checkout master
          - git pull
          - python setup.py build
          - cd build/*
          - tar -cvf DBooru.tar *
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"DBooru.tar"